### PR TITLE
initial approach to have possibility to start own supervisor for diff...

### PR DESCRIPTION
**Pull request by liveforeverx**
…erent handlers

It is not thought for merge, but the question, why the interface is so inflexible? If you want to change the path, you need to set environment, before starting the fs application (that leads, that on all places, where library is used, developers simply subscribe to cwd, which is default and checking the needed pattern for the path). And, it is not possible to create more, than one.

I think, there should be interface for it, for creating supervisors in own tree.

Simple attemp to add interface with start_link/4 (which get 3 names and path and it is still ugly), but want to try, that it works.

2 changes, which I want to reach:
- possibility to specify directory directly
- start more, that one handler

What do you think about it in general?

### CODE REVIEW

**Comment by liveforeverx** [comment]
Related to #12

**Comment by liveforeverx** [comment]
Ok, I've simplified the interface, to set only one name. Than, it should be seen as proposal.

What do you think about?

**Comment by liveforeverx** [comment]
Added backwards compatibility to original API.

**Comment by 5HT** [comment]
If it works and you'll be ready for catching all possible issues after merge then I can merge your change-set. Did you check that phoenix live reload plugin still works ?

**Comment by liveforeverx** [comment]
@5HT It works, I have tested and phoenix_live_reload still works. I've added information in README about `backwards_compatibility`. I'm definitely ready for catching all possible issues. I'm watching now for issues this repository.

**Comment by 5HT** [comment]
Well then thanks and welcome. I'm mergin' and will review code later.
We need to remove old code after `phoenix_live_reload` and `active` will switch to new schema.

**Pull request merged**
